<?php
use CustomerDomain\Entity\CustomerEntity;

$tableColumns = [
    'id'         => 'ID',
    'first_name' => 'Vorname',
    'last_name'  => 'Nachname',
    'country'    => 'Land',
];

$customerList = [];

/**
 * @var CustomerEntity $customerEntity
 */
foreach ($this->customerList as $customerEntity) {
    $customerList[$customerEntity->getId()] = [
        'id'         => $customerEntity->getId(),
        'first_name' => $customerEntity->getFirstName(),
        'last_name'  => $customerEntity->getLastName(),
        'country'    => $this->customerCountry(
            $customerEntity->getCountry()
        ),
    ];
}
?>

<h1>Kunden</h1>
<p>Hallo <?= $this->name ?></p>

<?= $this->applicationTable($customerList, $tableColumns, 'customer'); ?>

