<?php
$tableColumns = [
    'id'        => 'ID',
    'first_name' => 'Vorname',
    'last_name' => 'Nachname',
    'country'   => 'Land',
];

$customerList = $this->customerList;

foreach ($customerList as $customerKey => $customerValues) {
    $customerList[$customerKey]['country'] = $this->customerCountry(
        $customerValues['country']
    );
}
?>

<h1>Kunden</h1>
<p>Hallo <?= $this->name ?></p>

<?= $this->applicationTable($customerList, $tableColumns, 'customer'); ?>

