<?php
use CustomerDomain\Entity\CustomerEntity;

/** @var CustomerEntity $customer */
$customer = $this->customer;
?>

<h1>Kunden</h1>

<table class="table">
  <tbody>
    <tr>
      <td>ID</td>
      <td><?= $customer->getId() ?></td>
    </tr>
    <tr>
      <td>Vorname</td>
      <td><?= $customer->getFirstName() ?></td>
    </tr>
    <tr>
      <td>Nachname</td>
      <td><?= $customer->getLastName() ?></td>
    </tr>
    <tr>
      <td>Land</td>
      <td><?= $this->customerCountry($customer->getCountry()) ?></td>
    </tr>
  </tbody>
</table>
<hr>
<a href="<?= $this->url('customer') ?>" class="btn btn-primary">
  Kundenliste
</a>
